language: node_js
node_js:
  - '6'
  - '8'
  - '10'
cache:
  directories:
    - node_modules
stages:
  - test
  - name: saucelabs
    if: env(SAUCE_USERNAME) IS present
jobs:
  include:
    - stage: saucelabs
      node_js: '10'
      script: grunt saucelabs
      addons:
        sauce_connect: true
